#!/bin/bash

tempfile=$(mktemp)
minimal="tests/minimal.lua"
plugins_dir="./.tests/site/pack/deps/start"

function setup_environment() {
  echo
  echo "[test] setting up environment"
  echo

  if [[ ! -d "${plugins_dir}" ]]; then
    mkdir -p "${plugins_dir}"
  fi

  if [[ ! -d "${plugins_dir}/mini.test" ]]; then
    echo "[plugins] mini.test: installing..."
    git clone git@github.com:nvim-mini/mini.test.git "${plugins_dir}/mini.test"
    echo "[plugins] mini.test: installed"
    echo
  fi

  echo "[test] environment ready"
  echo
}

setup_environment

if [[ -n $1 ]]; then
  echo "Running tests with $1 not allowed yet"
  exit 1
else
  nvim --headless --noplugin -u ${minimal} \
    -c "lua require('mini.test').setup({collect = { find_files = function() return vim.fn.globpath('tests', '**/*_spec.lua', true, true) end,},})" \
    -c "lua require('mini.test').run()" |
    tee "${tempfile}"
fi

rm "${tempfile}"

if [[ -n $errors ]]; then
  echo "Tests failed"
  exit 1
fi

exit 0
