#!/bin/bash
# Adapted from https://github.com/nvim-neotest/neotest/blob/master/scripts/test

tempfile=$(mktemp)
minimal="tests/minimal.lua"

function luacov_start() {
  luacov_dir="$(dirname "$(luarocks which luacov 2>/dev/null | head -1)")"
  if [[ "${luacov_dir}" == "." ]]; then
    luacov_dir=""
  fi

  if test -n "${luacov_dir}"; then
    rm -f luacov.*.out
    export LUA_PATH=";;${luacov_dir}/?.lua"
  fi
}

function luacov_end() {
  if test -n "${luacov_dir}"; then
    if test -f "luacov.stats.out"; then
      luacov

      echo
      tail -n +$(($(grep -n "^Summary$" luacov.report.out | cut -d":" -f1) - 1)) luacov.report.out
    fi
  fi
}

luacov_start

if [[ -n $1 ]] && [[ $1 == "--fail-fast" ]]; then
  echo "Running tests with --fail-fast"
  nvim --headless --noplugin -u ${minimal} \
    -c "PlenaryBustedDirectory tests/ {minimal_init = '${minimal}', sequential = true, keep_going = false}" | tee "${tempfile}"
elif [[ -n $1 ]]; then
  nvim --headless --noplugin -u ${minimal} -c "PlenaryBustedFile $1" | tee "${tempfile}"
else
  nvim --headless --noplugin -u ${minimal} \
    -c "PlenaryBustedDirectory tests/ {minimal_init = '${minimal}'}" | tee "${tempfile}"
fi

luacov_end

# Plenary doesn't emit exit code 1 when tests have errors during setup
errors=$(sed 's/\x1b\[[0-9;]*m//g' "${tempfile}" | awk '/(Errors|Failed) :/ {print $3}' | grep -v '0')

rm "${tempfile}"

if [[ -n $errors ]]; then
  echo "Tests failed"
  exit 1
fi

exit 0
