#!/bin/bash

tempfile=$(mktemp)
minimal="tests/minimal.lua"

nvim --headless --noplugin -u ${minimal} \
  -c "lua require('plenary.test_harness').test_directory('./tests/', { minimal_init = 'tests/minimal.lua', sequential = false })" | tee "${tempfile}"

# Plenary doesn't emit exit code 1 when tests have errors during setup
errors=$(sed 's/\x1b\[[0-9;]*m//g' "${tempfile}" | awk '/(Errors|Failed) :/ {print $3}' | grep -v '0')

rm "${tempfile}"

if [[ -n $errors ]]; then
  echo "Tests failed"
  exit 1
fi

exit 0
