---@enum (key) ascii-ui.UserInteractions.InteractionType
local INTERACTION_TYPE = {
	SELECT = "SELECT",
	HOVER = "HOVER",
	CURSOR_MOVE_RIGHT = "CURSOR_MOVE_RIGHT",
	CURSOR_MOVE_LEFT = "CURSOR_MOVE_LEFT",
	CURSOR_MOVE_DOWN = "CURSOR_MOVE_DOWN",
	CURSOR_MOVE_UP = "CURSOR_MOVE_UP",
	INPUT = "INPUT",
}

return INTERACTION_TYPE
