pcall(require, "luacov")

local Color = require("ascii-ui.color")
local Segment = require("ascii-ui.buffer.segment")
local eq = assert.are.same

describe("Color", function()
	describe("new", function()
		it("creates color from table with fg", function()
			local c = Color.new({ fg = "#ff0000" })
			eq("#ff0000", c.fg)
			eq(nil, c.bg)
		end)

		it("creates color from table with bg", function()
			local c = Color.new({ bg = "#00ff00" })
			eq(nil, c.fg)
			eq("#00ff00", c.bg)
		end)

		it("creates color from table with fg and bg", function()
			local c = Color.new({ fg = "#ff0000", bg = "#0000ff" })
			eq("#ff0000", c.fg)
			eq("#0000ff", c.bg)
		end)

		it("creates color from string shorthand (treated as fg)", function()
			local c = Color.new("#ff0000")
			eq("#ff0000", c.fg)
			eq(nil, c.bg)
		end)

		it("normalizes hex to lowercase", function()
			local c = Color.new("#FF00AA")
			eq("#ff00aa", c.fg)
		end)

		it("adds # prefix if missing", function()
			local c = Color.new("ff00aa")
			eq("#ff00aa", c.fg)
		end)

		it("expands 3-char hex to 6-char", function()
			local c = Color.new("#f0a")
			eq("#ff00aa", c.fg)
		end)

		it("caches identical colors", function()
			local c1 = Color.new("#ff0000")
			local c2 = Color.new("#ff0000")
			assert.is_true(c1 == c2) -- same instance
		end)

		it("caches table and string with same fg", function()
			local c1 = Color.new("#ff0000")
			local c2 = Color.new({ fg = "#ff0000" })
			assert.is_true(c1 == c2) -- same instance
		end)

		it("returns same instance if passed a Color", function()
			local c1 = Color.new("#ff0000")
			local c2 = Color.new(c1)
			assert.is_true(c1 == c2)
		end)

		it("errors on invalid input type", function()
			assert.has_error(function()
				Color.new(123)
			end)
		end)
	end)

	describe("to_hl_group", function()
		it("creates a highlight group name", function()
			local c = Color.new({ fg = "#ff0000", bg = "#00ff00" })
			local hl = c:to_hl_group()
			assert.is_truthy(hl:find("AsciiUI_fg"))
			assert.is_truthy(hl:find("ff0000"))
			assert.is_truthy(hl:find("00ff00"))
		end)

		it("caches highlight groups", function()
			local c1 = Color.new("#ff0000")
			local c2 = Color.new("#ff0000")
			eq(c1:to_hl_group(), c2:to_hl_group())
		end)

		it("handles fg only", function()
			local c = Color.new({ fg = "#ff0000" })
			local hl = c:to_hl_group()
			assert.is_truthy(hl:find("NONE"))
		end)

		it("handles bg only", function()
			local c = Color.new({ bg = "#00ff00" })
			local hl = c:to_hl_group()
			assert.is_truthy(hl:find("NONE"))
		end)
	end)

	describe("to_ansi", function()
		it("returns fg ANSI code", function()
			local c = Color.new({ fg = "#ff0000" })
			local ansi = c:to_ansi()
			-- ESC[38;2;255;0;0m
			assert.is_truthy(ansi:find("\027%[38;2;255;0;0m"))
		end)

		it("returns bg ANSI code", function()
			local c = Color.new({ bg = "#00ff00" })
			local ansi = c:to_ansi()
			-- ESC[48;2;0;255;0m
			assert.is_truthy(ansi:find("\027%[48;2;0;255;0m"))
		end)

		it("returns both fg and bg ANSI codes", function()
			local c = Color.new({ fg = "#ff0000", bg = "#0000ff" })
			local ansi = c:to_ansi()
			assert.is_truthy(ansi:find("\027%[38;2;255;0;0m"))
			assert.is_truthy(ansi:find("\027%[48;2;0;0;255m"))
		end)

		it("returns empty string for empty color", function()
			local c = Color.new({})
			eq("", c:to_ansi())
		end)
	end)

	describe("is_empty", function()
		it("returns true when neither fg nor bg set", function()
			local c = Color.new({})
			assert.is_true(c:is_empty())
		end)

		it("returns false when fg set", function()
			local c = Color.new({ fg = "#ff0000" })
			assert.is_false(c:is_empty())
		end)

		it("returns false when bg set", function()
			local c = Color.new({ bg = "#00ff00" })
			assert.is_false(c:is_empty())
		end)

		it("returns false when both set", function()
			local c = Color.new({ fg = "#ff0000", bg = "#00ff00" })
			assert.is_false(c:is_empty())
		end)
	end)

	describe("is_color", function()
		it("returns true for Color instance", function()
			local c = Color.new("#ff0000")
			assert.is_true(Color.is_color(c))
		end)

		it("returns false for plain table", function()
			assert.is_false(Color.is_color({ fg = "#ff0000" }))
		end)

		it("returns false for nil", function()
			assert.is_false(Color.is_color(nil))
		end)

		it("returns false for string", function()
			assert.is_false(Color.is_color("#ff0000"))
		end)
	end)
end)

describe("Segment color shorthand", function()
	it("accepts string color as fg shorthand", function()
		local seg = Segment:new({ content = "test", color = "#ff0000" })
		eq({ fg = "#ff0000" }, seg.color)
	end)

	it("accepts table color", function()
		local seg = Segment:new({ content = "test", color = { fg = "#ff0000", bg = "#00ff00" } })
		eq({ fg = "#ff0000", bg = "#00ff00" }, seg.color)
	end)

	it("accepts Color instance", function()
		local c = Color.new("#ff0000")
		local seg = Segment:new({ content = "test", color = c })
		assert.is_true(Color.is_color(seg.color))
		eq("#ff0000", seg.color.fg)
	end)

	it("handles nil color", function()
		local seg = Segment:new({ content = "test" })
		eq(nil, seg.color)
	end)

	it("is_colored works with string shorthand", function()
		local seg = Segment:new({ content = "test", color = "#ff0000" })
		assert.is_true(seg:is_colored())
	end)

	it("is_colored works with table", function()
		local seg = Segment:new({ content = "test", color = { fg = "#ff0000" } })
		assert.is_true(seg:is_colored())
	end)

	it("is_colored works with Color instance", function()
		local c = Color.new("#ff0000")
		local seg = Segment:new({ content = "test", color = c })
		assert.is_true(seg:is_colored())
	end)
end)
